[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: force Next.js to use Netlify Edge/Functions where possible
# [functions]
#   node_bundler = "esbuild"
#   included_files = ["public/**"]
